import type { NextPage } from "next";
import Head from "next/head";
import { useSkylarkSchema } from "../hooks/useSkylarkSchema";

const Home: NextPage = () => {
  // #1st -> Select type (ex: Episode)
  // get all fields from episode from graphql
  // get all inputs for create mutation ?

  // 2nd
  // upload the csv ?

  // 3rd
  // upload from flatfile to skylark using mutation and matched fields

  const mutations = useSkylarkSchema();

  return (
    <div>
      <Head>
        <title>FlatFile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-screen h-screen justify-center items-center">
        <p className="text-5xl animate-bounce">James Wallis rocks</p>
      </main>

      <div></div>

      <footer></footer>
    </div>
  );
};

export default Home;
