import type { NextPage } from "next";
import Head from "next/head";
import { getMutations } from "../hooks/getMutations";

import { useInput } from "../hooks/useInput";
import { createTemplate } from "../lib/template";

const Template: NextPage = () => {
  // #1st -> Select type (ex: Episode)
  // get all fields from episode from graphql
  // get all inputs for create mutation ?

  // 2nd
  // upload the csv ?

  // 3rd
  // upload from flatfile to skylark using mutation and matched fields

  return (
    <div>
      <Head>
        <title>FlatFile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-screen h-screen justify-center items-center">
        <button className="p-2 px-5 text-white bg-blue-600 rounded" onClick={() => createTemplate()}>Create template</button>
      </main>

      <div></div>

      <footer></footer>
    </div>
  );
};

export default Template;
