import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { createTemplate, getTemplates } from "../lib/template";

const Template: NextPage = () => {
  const [data, setData] = useState("");

  return (
    <div className="flex justify-center">
      <Head>
        <title>FlatFile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen mt-10  flex justify-center flex-col max-w-3xl">
        <div className="flex justify-center items-start gap-4 mb-20">
          <button className="p-2 px-5 text-white bg-blue-600 rounded" onClick={async() => setData(await getTemplates())}>Get templates</button>
          <button className="p-2 px-5 text-white bg-blue-600 rounded" onClick={async() => setData(await createTemplate())}>Create template</button>
        </div>

      <pre>
        {data}
      </pre>
      </main>

      <footer></footer>
    </div>
  );
};

export default Template;
